steps:

  # Step 2: Build the Training Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Training Image'
    args:
      - 'build'
      - '--network=cloudbuild'
      - '-t'
      - 'gcr.io/$PROJECT_ID/training-image'
      - '-f'
      - 'Dockerfile-training'
      - '.'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Fetch Service Account Key'
    entrypoint: 'gsutil'
    args:
      - 'cp'
      - 'gs://service-account-key-training/keys.json'
      - '/workspace/service-account-key.json'  # Ensure the file name matches throughout

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Run Docker Container'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/workspace:/workspace'  # This mounts the Cloud Build workspace inside the container
      - '-e'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/service-account-key.json'
      - 'gcr.io/$PROJECT_ID/training-image'

options:
  logging: CLOUD_LOGGING_ONLY
