steps:

  # Step 3: Build Training Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Training Image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/training-image'
      - '-f'
      - 'Dockerfile-training'
      - '.'

  # Step 4: Run Training Docker Container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Run Training Container'
    args:
      - 'run'
      - '--rm'
      - 'gcr.io/$PROJECT_ID/training-image'

options:
  logging: CLOUD_LOGGING_ONLY
