# Use the official Python image
FROM python:3.12-slim

# Install dependencies for mlflow tracking
RUN pip install --no-cache-dir pip==24.3.1 setuptools==75.6.0 wheel==0.43.0

# Install jq
RUN apt-get update && apt-get install -y jq

# Set the working directory
WORKDIR /app

# Copy application files
COPY . /app

# Install local requirements
RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x /app/entrypoint.sh

# Set the entrypoint script
ENTRYPOINT ["/app/entrypoint.sh"]