# Use the official Python image
FROM python:3.12-slim

# Install dependencies for MLflow tracking
RUN pip install --no-cache-dir pip==24.3.1 setuptools==75.6.0 wheel==0.43.0


# Set the working directory
WORKDIR /app

# Copy only app.py and requirements.txt
COPY app.py /app/
COPY requirements.txt /app/

# Install local requirements
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 8080

ENV TEST_RUN = false

# Run the application directly
CMD ["python", "app.py"]
