name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-local.txt

      # Authenticate with Google Cloud
      - name: Set up Google Cloud authentication
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud auth list  # Verify authentication
          export GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json

      # Run tests
      - name: Run tests
        run: |
           python -m pytest tests/  # Adjust this if you use a custom command to run tests