name: Run Tests

on:
  push:
    branches:
      - main  # Trigger only for pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Optionally, also run tests for PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use a fresh Ubuntu environment

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # Specify your Python version here

      # Install dependencies (assuming requirements.txt exists)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
           python -m pytest tests/  # Adjust this if you use a custom command to run tests