name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-local.txt

      # Authenticate with Google Cloud
      - name: Set up Google Cloud authentication
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > $HOME/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud auth list  # Verify authentication

      # Run tests
      - name: Run tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json  # Ensure it's available in the test environment
        run: |
           python -m pytest tests/  # Adjust this if you use a custom command to run tests